# Generated by Django 5.0.2 on 2024-02-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useraccount_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
    ]
