# Generated by Django 5.0.2 on 2024-02-21 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_useraccount_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=3, message='Minimum 3 characters required.')]),
        ),
    ]
